DOMAIN-SUFFIX,doubleclick.net
DOMAIN-SUFFIX,adnxs.com
DOMAIN,ads.stickyadstv.com
DOMAIN-SUFFIX,3lift.com
DOMAIN,adtracker.medproad.com
DOMAIN-SUFFIX,httpdns.alicdn.com
DOMAIN-SUFFIX,httpdns.pro
DOMAIN-SUFFIX,httpdns.c.cdnhwc2.com
DOMAIN-SUFFIX,mmstat.com
HOST,ulogs.umengcloud.com
HOST,adashx.ut.amap.com
HOST,optimus-ads.amap.com
DOMAIN-SUFFIX,dualstack-logs.amap.com
DOMAIN-SUFFIX,logs.amap.com
DOMAIN-SUFFIX,optimus-ads.amap.com
DOMAIN-SUFFIX,ali-stats.jpush.cn
DOMAIN-SUFFIX,51gowan.com
DOMAIN-SUFFIX,sogowan.com
DOMAIN-SUFFIX,gowan.com

# Google
DOMAIN-SUFFIX,adtrafficquality.google
DOMAIN-SUFFIX,ads.google.cn
DOMAIN-SUFFIX,adsense.google.cn
DOMAIN-SUFFIX,adservice.google.cn
DOMAIN-SUFFIX,adservice.google.com
DOMAIN-SUFFIX,afs.googlesyndication.com
DOMAIN-SUFFIX,analytics.google.com
DOMAIN-SUFFIX,click.googleanalytics.com
DOMAIN-SUFFIX,crashlyticsreports-pa.googleapis.com
DOMAIN-SUFFIX,firebaselogging-pa.googleapis.com
DOMAIN-SUFFIX,google-analytics.com
DOMAIN-SUFFIX,googleads.g.doubleclick.net
DOMAIN-SUFFIX,googleadservices-cn.com
DOMAIN-SUFFIX,googleadservices.com
DOMAIN-SUFFIX,googletagservices-cn.com
DOMAIN-SUFFIX,googletagservices.com
DOMAIN-SUFFIX,pagead2.googleadservices.com
DOMAIN-SUFFIX,pagead2.googlesyndication.com

# 运营商广告
DOMAIN-SUFFIX,114so.cn
DOMAIN-SUFFIX,go.10086.cn
DOMAIN-SUFFIX,hivedata.cc
DOMAIN-SUFFIX,navi.gd.chinamobile.com

# 广告联盟（国内）
DOMAIN-SUFFIX,09mk.cn
DOMAIN-SUFFIX,100peng.com
DOMAIN-SUFFIX,114la.com
DOMAIN-SUFFIX,123juzi.net
DOMAIN-SUFFIX,138lm.com
DOMAIN-SUFFIX,17un.com
DOMAIN-SUFFIX,2cnt.net
DOMAIN-SUFFIX,3gmimo.com
DOMAIN-SUFFIX,3xx.vip
DOMAIN-SUFFIX,51.la
DOMAIN-SUFFIX,51taifu.com
DOMAIN-SUFFIX,51yes.com
DOMAIN-SUFFIX,600ad.com
DOMAIN-SUFFIX,6dad.com
DOMAIN-SUFFIX,70e.com
DOMAIN-SUFFIX,86.cc
DOMAIN-SUFFIX,8le8le.com
DOMAIN-SUFFIX,8ox.cn
DOMAIN-SUFFIX,95558000.com
DOMAIN-SUFFIX,99click.com
DOMAIN-SUFFIX,99youmeng.com
DOMAIN-SUFFIX,a3p4.net
DOMAIN-SUFFIX,acs86.com
DOMAIN-SUFFIX,acxiom-online.com
DOMAIN-SUFFIX,ad-brix.com
DOMAIN-SUFFIX,ad-delivery.net
DOMAIN-SUFFIX,ad-locus.com
DOMAIN-SUFFIX,ad-plus.cn
DOMAIN-SUFFIX,ad7.com
DOMAIN-SUFFIX,adadapted.com
DOMAIN-SUFFIX,adadvisor.net
DOMAIN-SUFFIX,adap.tv
DOMAIN-SUFFIX,adbana.com
DOMAIN-SUFFIX,adchina.com
DOMAIN-SUFFIX,adcome.cn
DOMAIN-SUFFIX,ader.mobi
DOMAIN-SUFFIX,adform.net
DOMAIN-SUFFIX,adfuture.cn
DOMAIN-SUFFIX,adhouyi.com
DOMAIN-SUFFIX,adinfuse.com
DOMAIN-SUFFIX,adirects.com
DOMAIN-SUFFIX,adjust.io
DOMAIN-SUFFIX,adkmob.com
DOMAIN-SUFFIX,adlive.cn
DOMAIN-SUFFIX,adlocus.com
DOMAIN-SUFFIX,admaji.com
DOMAIN-SUFFIX,admin6.com
DOMAIN-SUFFIX,admon.cn
DOMAIN-SUFFIX,adnyg.com
DOMAIN-SUFFIX,adpolestar.net
DOMAIN-SUFFIX,adpro.cn
DOMAIN-SUFFIX,adpush.cn
DOMAIN-SUFFIX,adquan.com
DOMAIN-SUFFIX,adreal.cn
DOMAIN-SUFFIX,ads8.com
DOMAIN-SUFFIX,adsame.com
DOMAIN-SUFFIX,adsmogo.com
DOMAIN-SUFFIX,adsmogo.org
DOMAIN-SUFFIX,adsunflower.com
DOMAIN-SUFFIX,adsunion.com
DOMAIN-SUFFIX,adtrk.me
DOMAIN-SUFFIX,adups.com
DOMAIN-SUFFIX,aduu.cn
DOMAIN-SUFFIX,advertising.com
DOMAIN-SUFFIX,adview.cn
DOMAIN-SUFFIX,advmob.cn
DOMAIN-SUFFIX,adwetec.com
DOMAIN-SUFFIX,adwhirl.com
DOMAIN-SUFFIX,adwo.com
DOMAIN-SUFFIX,adxmi.com
DOMAIN-SUFFIX,adyun.com
DOMAIN-SUFFIX,adzerk.net
DOMAIN-SUFFIX,agrant.cn
DOMAIN-SUFFIX,agrantsem.com
DOMAIN-SUFFIX,aihaoduo.cn
DOMAIN-SUFFIX,ajapk.com
DOMAIN-SUFFIX,allyes.cn
DOMAIN-SUFFIX,allyes.com
DOMAIN-SUFFIX,amazon-adsystem.com
DOMAIN-SUFFIX,analysys.cn
DOMAIN-SUFFIX,angsrvr.com
DOMAIN-SUFFIX,anquan.org
DOMAIN-SUFFIX,anysdk.com
DOMAIN-SUFFIX,appadhoc.com
DOMAIN-SUFFIX,appads.com
DOMAIN-SUFFIX,appboy.com
DOMAIN-SUFFIX,appdriver.cn
DOMAIN-SUFFIX,appjiagu.com
DOMAIN-SUFFIX,applifier.com
DOMAIN-SUFFIX,appsflyer.com
DOMAIN-SUFFIX,atdmt.com
DOMAIN-SUFFIX,baifendian.com
DOMAIN-SUFFIX,banmamedia.com
DOMAIN-SUFFIX,baoyatu.cc
DOMAIN-SUFFIX,baycode.cn
DOMAIN-SUFFIX,bayimob.com
DOMAIN-SUFFIX,behe.com
DOMAIN-SUFFIX,bfshan.cn
DOMAIN-SUFFIX,biddingos.com
DOMAIN-SUFFIX,biddingx.com
DOMAIN-SUFFIX,bjvvqu.cn
DOMAIN-SUFFIX,bjxiaohua.com
DOMAIN-SUFFIX,bloggerads.net
DOMAIN-SUFFIX,branch.io
DOMAIN-SUFFIX,bsdev.cn
DOMAIN-SUFFIX,bshare.cn
DOMAIN-SUFFIX,btyou.com
DOMAIN-SUFFIX,bugtags.com
DOMAIN-SUFFIX,buysellads.com
DOMAIN-SUFFIX,c0563.com
DOMAIN-SUFFIX,cacafly.com
DOMAIN-SUFFIX,casee.cn
DOMAIN-SUFFIX,cdnmaster.com
DOMAIN-SUFFIX,chance-ad.com
DOMAIN-SUFFIX,chanet.com.cn
DOMAIN-SUFFIX,chartbeat.com
DOMAIN-SUFFIX,chartboost.com
DOMAIN-SUFFIX,chengadx.com
DOMAIN-SUFFIX,chmae.com
DOMAIN-SUFFIX,clickadu.com
DOMAIN-SUFFIX,clicki.cn
DOMAIN-SUFFIX,clicktracks.com
DOMAIN-SUFFIX,clickzs.com
DOMAIN-SUFFIX,cloudmobi.net
DOMAIN-SUFFIX,cmcore.com
DOMAIN-SUFFIX,cnxad.com
DOMAIN-SUFFIX,cnzz.com
DOMAIN-SUFFIX,cnzz.net
DOMAIN-SUFFIX,cnzz.cn
DOMAIN-SUFFIX,cnzzlink.com
DOMAIN-SUFFIX,cocounion.com
DOMAIN-SUFFIX,coocaatv.com
DOMAIN-SUFFIX,cooguo.com
DOMAIN-SUFFIX,coolguang.com
DOMAIN-SUFFIX,coremetrics.com
DOMAIN-SUFFIX,cpmchina.co
DOMAIN-SUFFIX,cpx24.com
DOMAIN-SUFFIX,crasheye.cn
DOMAIN-SUFFIX,crosschannel.com
DOMAIN-SUFFIX,ctrmi.com
DOMAIN-SUFFIX,customer-security.online
DOMAIN-SUFFIX,daoyoudao.com
DOMAIN-SUFFIX,datouniao.com
DOMAIN-SUFFIX,ddapp.cn
DOMAIN-SUFFIX,dianjoy.com
DOMAIN-SUFFIX,dianru.com
DOMAIN-SUFFIX,disqusads.com
DOMAIN-SUFFIX,domob.cn
DOMAIN-SUFFIX,domob.com.cn
DOMAIN-SUFFIX,domob.org
DOMAIN-SUFFIX,dotmore.com.tw
DOMAIN-SUFFIX,doubleverify.com
DOMAIN-SUFFIX,doudouguo.com
DOMAIN-SUFFIX,doumob.com
DOMAIN-SUFFIX,duanat.com
DOMAIN-SUFFIX,duiba.com.cn
DOMAIN-SUFFIX,duomeng.cn
DOMAIN-SUFFIX,dxpmedia.com
DOMAIN-SUFFIX,edigitalsurvey.com
DOMAIN-SUFFIX,eduancm.com
DOMAIN-SUFFIX,emarbox.com
DOMAIN-SUFFIX,exosrv.com
DOMAIN-SUFFIX,fancyapi.com
DOMAIN-SUFFIX,feitian001.com
DOMAIN-SUFFIX,feixin2.com
DOMAIN-SUFFIX,flashtalking.com
DOMAIN-SUFFIX,fraudmetrix.cn
DOMAIN-SUFFIX,g1.tagtic.cn
DOMAIN-SUFFIX,gentags.net
DOMAIN-SUFFIX,gepush.com
DOMAIN-SUFFIX,getui.com
DOMAIN-SUFFIX,glispa.com
DOMAIN-SUFFIX,go-mpulse
DOMAIN-SUFFIX,go-mpulse.net
DOMAIN-SUFFIX,godloveme.cn
DOMAIN-SUFFIX,gridsum.com
DOMAIN-SUFFIX,gridsumdissector.cn
DOMAIN-SUFFIX,gridsumdissector.com
DOMAIN-SUFFIX,growingio.com
DOMAIN-SUFFIX,guohead.com
DOMAIN-SUFFIX,guomob.com
DOMAIN-SUFFIX,haoghost.com
DOMAIN-SUFFIX,hivecn.cn
DOMAIN-SUFFIX,hypers.com
DOMAIN-SUFFIX,icast.cn
DOMAIN-SUFFIX,igexin.com
DOMAIN-SUFFIX,il8r.com
DOMAIN-SUFFIX,imageter.com
DOMAIN-SUFFIX,immob.cn
DOMAIN-SUFFIX,inad.com
DOMAIN-SUFFIX,inmobi.cn
DOMAIN-SUFFIX,inmobi.net
DOMAIN-SUFFIX,inmobicdn.cn
DOMAIN-SUFFIX,inmobicdn.net
DOMAIN-SUFFIX,innity.com
DOMAIN-SUFFIX,instabug.com
DOMAIN-SUFFIX,intely.cn
DOMAIN-SUFFIX,iperceptions.com
DOMAIN-SUFFIX,ipinyou.com
DOMAIN-SUFFIX,irs01.com
DOMAIN-SUFFIX,irs01.net
DOMAIN-SUFFIX,irs09.com
DOMAIN-SUFFIX,istreamsche.com
DOMAIN-SUFFIX,jesgoo.com
DOMAIN-SUFFIX,jiaeasy.net
DOMAIN-SUFFIX,jiguang.cn
DOMAIN-SUFFIX,jimdo.com
DOMAIN-SUFFIX,jisucn.com
DOMAIN-SUFFIX,jmgehn.cn
DOMAIN-SUFFIX,jpush.cn
DOMAIN-SUFFIX,jusha.com
DOMAIN-SUFFIX,juzi.cn
DOMAIN-SUFFIX,juzilm.com
DOMAIN-SUFFIX,kejet.com
DOMAIN-SUFFIX,kejet.net
DOMAIN-SUFFIX,keydot.net
DOMAIN-SUFFIX,keyrun.cn
DOMAIN-SUFFIX,kmd365.com
DOMAIN-SUFFIX,krux.net
DOMAIN-SUFFIX,lnk0.com
DOMAIN-SUFFIX,lnk8.cn
DOMAIN-SUFFIX,localytics.com
DOMAIN-SUFFIX,lomark.cn
DOMAIN-SUFFIX,lotuseed.com
DOMAIN-SUFFIX,lrswl.com
DOMAIN-SUFFIX,lufax.com
DOMAIN-SUFFIX,madhouse.cn
DOMAIN-SUFFIX,madmini.com
DOMAIN-SUFFIX,madserving.com
DOMAIN-SUFFIX,magicwindow.cn
DOMAIN-SUFFIX,mathtag.com
DOMAIN-SUFFIX,maysunmedia.com
DOMAIN-SUFFIX,mbai.cn
DOMAIN-SUFFIX,mediaplex.com
DOMAIN-SUFFIX,mediav.com
DOMAIN-SUFFIX,megajoy.com
DOMAIN-SUFFIX,mgogo.com
DOMAIN-SUFFIX,miaozhen.com
DOMAIN-SUFFIX,microad-cn.com
DOMAIN-SUFFIX,miidi.net
DOMAIN-SUFFIX,mijifen.com
DOMAIN-SUFFIX,mixpanel.com
DOMAIN-SUFFIX,mjmobi.com
DOMAIN-SUFFIX,mng-ads.com
DOMAIN-SUFFIX,moad.cn
DOMAIN-SUFFIX,moatads.com
DOMAIN-SUFFIX,mobaders.com
DOMAIN-SUFFIX,mobclix.com
DOMAIN-SUFFIX,mobgi.com
DOMAIN-SUFFIX,mobisage.cn
DOMAIN-SUFFIX,mobvista.com
DOMAIN-SUFFIX,moogos.com
DOMAIN-SUFFIX,mopub.com
DOMAIN-SUFFIX,moquanad.com
DOMAIN-SUFFIX,mpush.cn
DOMAIN-SUFFIX,mxpnl.com
DOMAIN-SUFFIX,myhug.cn
DOMAIN-SUFFIX,mzy2014.com
DOMAIN-SUFFIX,networkbench.com
DOMAIN-SUFFIX,ninebox.cn
DOMAIN-SUFFIX,ntalker.com
DOMAIN-SUFFIX,nylalobghyhirgh.com
DOMAIN-SUFFIX,o2omobi.com
DOMAIN-SUFFIX,oadz.com
DOMAIN-SUFFIX,oneapm.com
DOMAIN-SUFFIX,onetad.com
DOMAIN-SUFFIX,optaim.com
DOMAIN-SUFFIX,optimix.asia
DOMAIN-SUFFIX,optimix.cn
DOMAIN-SUFFIX,optimizelyapis.com
DOMAIN-SUFFIX,overture.com
DOMAIN-SUFFIX,p0y.cn
DOMAIN-SUFFIX,pagechoice.net
DOMAIN-SUFFIX,pingdom.net
DOMAIN-SUFFIX,plugrush.com
DOMAIN-SUFFIX,popin.cc
DOMAIN-SUFFIX,pro.cn
DOMAIN-SUFFIX,publicidad.net
DOMAIN-SUFFIX,publicidad.tv
DOMAIN-SUFFIX,pubmatic.com
DOMAIN-SUFFIX,pubnub.com
DOMAIN-SUFFIX,qcl777.com
DOMAIN-SUFFIX,qiyou.com
DOMAIN-SUFFIX,qtmojo.com
DOMAIN-SUFFIX,quantcount.com
DOMAIN-SUFFIX,qucaigg.com
DOMAIN-SUFFIX,qumi.com
DOMAIN-SUFFIX,qxxys.com
DOMAIN-SUFFIX,reachmax.cn
DOMAIN-SUFFIX,responsys.net
DOMAIN-SUFFIX,revsci.net
DOMAIN-SUFFIX,rlcdn.com
DOMAIN-SUFFIX,rtbasia.com
DOMAIN-SUFFIX,sanya1.com
DOMAIN-SUFFIX,scupio.com
DOMAIN-SUFFIX,serving-sys.com
DOMAIN-SUFFIX,shuiguo.com
DOMAIN-SUFFIX,shuzilm.cn
DOMAIN-SUFFIX,similarweb.com
DOMAIN-SUFFIX,sitemeter.com
DOMAIN-SUFFIX,sitescout.com
DOMAIN-SUFFIX,sitetag.us
DOMAIN-SUFFIX,smartmad.com
DOMAIN-SUFFIX,social-touch.com
DOMAIN-SUFFIX,somecoding.com
DOMAIN-SUFFIX,sponsorpay.com
DOMAIN-SUFFIX,stargame.com
DOMAIN-SUFFIX,stg8.com
DOMAIN-SUFFIX,switchadhub.com
DOMAIN-SUFFIX,sycbbs.com
DOMAIN-SUFFIX,synacast.com
DOMAIN-SUFFIX,sysdig.com
DOMAIN-SUFFIX,talkingdata.com
DOMAIN-SUFFIX,talkingdata.net
DOMAIN-SUFFIX,tansuotv.com
DOMAIN-SUFFIX,tanv.com
DOMAIN-SUFFIX,tanx.com
DOMAIN-SUFFIX,tapjoy.cn
DOMAIN-SUFFIX,th7.cn
DOMAIN-SUFFIX,thoughtleadr.com
DOMAIN-SUFFIX,tianmidian.com
DOMAIN-SUFFIX,tiqcdn.com
DOMAIN-SUFFIX,touclick.com
DOMAIN-SUFFIX,trafficjam.cn
DOMAIN-SUFFIX,trafficmp.com
DOMAIN-SUFFIX,tuia.cn
DOMAIN-SUFFIX,ueadlian.com
DOMAIN-SUFFIX,uerzyr.cn
DOMAIN-SUFFIX,ugdtimg.com
DOMAIN-SUFFIX,ugvip.com
DOMAIN-SUFFIX,ujian.cc
DOMAIN-SUFFIX,ukeiae.com
DOMAIN-SUFFIX,umeng.co
DOMAIN-SUFFIX,umeng.com
DOMAIN-SUFFIX,umtrack.com
DOMAIN-SUFFIX,unimhk.com
DOMAIN-SUFFIX,union-wifi.com
DOMAIN-SUFFIX,union001.com
DOMAIN-SUFFIX,unionsy.com
DOMAIN-SUFFIX,unlitui.com
DOMAIN-SUFFIX,uri6.com
DOMAIN-SUFFIX,ushaqi.com
DOMAIN-SUFFIX,usingde.com
DOMAIN-SUFFIX,uuzu.com
DOMAIN-SUFFIX,uyunad.com
DOMAIN-SUFFIX,vamaker.com
DOMAIN-SUFFIX,vlion.cn
DOMAIN-SUFFIX,voiceads.cn
DOMAIN-SUFFIX,voiceads.com
DOMAIN-SUFFIX,vpon.com
DOMAIN-SUFFIX,vungle.cn
DOMAIN-SUFFIX,vungle.com
DOMAIN-SUFFIX,waps.cn
DOMAIN-SUFFIX,wapx.cn
DOMAIN-SUFFIX,webterren.com
DOMAIN-SUFFIX,whpxy.com
DOMAIN-SUFFIX,winads.cn
DOMAIN-SUFFIX,winasdaq.com
DOMAIN-SUFFIX,wiyun.com
DOMAIN-SUFFIX,wooboo.com.cn
DOMAIN-SUFFIX,wqmobile.com
DOMAIN-SUFFIX,wrating.com
DOMAIN-SUFFIX,wumii.cn
DOMAIN-SUFFIX,xcy8.com
DOMAIN-SUFFIX,xdrig.com
DOMAIN-SUFFIX,xiaozhen.com
DOMAIN-SUFFIX,xibao100.com
DOMAIN-SUFFIX,xtgreat.com
DOMAIN-SUFFIX,xy.com
DOMAIN-SUFFIX,yandui.com
DOMAIN-SUFFIX,yigao.com
DOMAIN-SUFFIX,yijifen.com
DOMAIN-SUFFIX,yinooo.com
DOMAIN-SUFFIX,yiqifa.com
DOMAIN-SUFFIX,yiwk.com
DOMAIN-SUFFIX,ylunion.com
DOMAIN-SUFFIX,ymapp.com
DOMAIN-SUFFIX,ymcdn.cn
DOMAIN-SUFFIX,yongyuelm.com
DOMAIN-SUFFIX,yooli.com
DOMAIN-SUFFIX,youmi.net
DOMAIN-SUFFIX,youxiaoad.com
DOMAIN-SUFFIX,yoyi.com.cn
DOMAIN-SUFFIX,yoyi.tv
DOMAIN-SUFFIX,yrxmr.com
DOMAIN-SUFFIX,ysjwj.com
DOMAIN-SUFFIX,yunjiasu.com
DOMAIN-SUFFIX,yunpifu.cn
DOMAIN-SUFFIX,zampdsp.com
DOMAIN-SUFFIX,zamplus.com
DOMAIN-SUFFIX,zcdsp.com
DOMAIN-SUFFIX,zhidian3g.cn
DOMAIN-SUFFIX,zhiziyun.com
DOMAIN-SUFFIX,zhjfad.com
DOMAIN-SUFFIX,zqzxz.com
DOMAIN-SUFFIX,zzsx8.com
DOMAIN-SUFFIX,wwads.cn

# 广告联盟（国外）
DOMAIN-SUFFIX,acuityplatform.com
DOMAIN-SUFFIX,ad-stir.com
DOMAIN-SUFFIX,ad-survey.com
DOMAIN-SUFFIX,ad4game.com
DOMAIN-SUFFIX,adcloud.jp
DOMAIN-SUFFIX,adcolony.com
DOMAIN-SUFFIX,addthis.com
DOMAIN-SUFFIX,adfurikun.jp
DOMAIN-SUFFIX,adhigh.net
DOMAIN-SUFFIX,adhood.com
DOMAIN-SUFFIX,adinall.com
DOMAIN-SUFFIX,adition.com
DOMAIN-SUFFIX,adk2x.com
DOMAIN-SUFFIX,admarket.mobi
DOMAIN-SUFFIX,admarvel.com
DOMAIN-SUFFIX,admedia.com
DOMAIN-SUFFIX,adnxs.com
DOMAIN-SUFFIX,adotmob.com
DOMAIN-SUFFIX,adperium.com
DOMAIN-SUFFIX,adriver.ru
DOMAIN-SUFFIX,adroll.com
DOMAIN-SUFFIX,adsco.re
DOMAIN-SUFFIX,adservice.com
DOMAIN-SUFFIX,adsrvr.org
DOMAIN-SUFFIX,adsymptotic.com
DOMAIN-SUFFIX,adtaily.com
DOMAIN-SUFFIX,adtech.de
DOMAIN-SUFFIX,adtechjp.com
DOMAIN-SUFFIX,adtechus.com
DOMAIN-SUFFIX,airpush.com
DOMAIN-SUFFIX,am15.net
DOMAIN-SUFFIX,amobee.com
DOMAIN-SUFFIX,appier.net
DOMAIN-SUFFIX,applift.com
DOMAIN-SUFFIX,apsalar.com
DOMAIN-SUFFIX,atas.io
DOMAIN-SUFFIX,awempire.com
DOMAIN-SUFFIX,axonix.com
DOMAIN-SUFFIX,beintoo.com
DOMAIN-SUFFIX,bepolite.eu
DOMAIN-SUFFIX,bidtheatre.com
DOMAIN-SUFFIX,bidvertiser.com
DOMAIN-SUFFIX,blismedia.com
DOMAIN-SUFFIX,brucelead.com
DOMAIN-SUFFIX,bttrack.com
DOMAIN-SUFFIX,casalemedia.com
DOMAIN-SUFFIX,celtra.com
DOMAIN-SUFFIX,channeladvisor.com
DOMAIN-SUFFIX,connexity.net
DOMAIN-SUFFIX,criteo.com
DOMAIN-SUFFIX,criteo.net
DOMAIN-SUFFIX,csbew.com
DOMAIN-SUFFIX,directrev.com
DOMAIN-SUFFIX,dumedia.ru
DOMAIN-SUFFIX,effectivemeasure.com
DOMAIN-SUFFIX,effectivemeasure.net
DOMAIN-SUFFIX,eqads.com
DOMAIN-SUFFIX,everesttech.net
DOMAIN-SUFFIX,exoclick.com
DOMAIN-SUFFIX,extend.tv
DOMAIN-SUFFIX,eyereturn.com
DOMAIN-SUFFIX,fastapi.net
DOMAIN-SUFFIX,fastclick.com
DOMAIN-SUFFIX,fastclick.net
DOMAIN-SUFFIX,flurry.com
DOMAIN-SUFFIX,gosquared.com
DOMAIN-SUFFIX,gtags.net
DOMAIN-SUFFIX,heyzap.com
DOMAIN-SUFFIX,histats.com
DOMAIN-SUFFIX,hitslink.com
DOMAIN-SUFFIX,hot-mob.com
DOMAIN-SUFFIX,hyperpromote.com
DOMAIN-SUFFIX,i-mobile.co.jp
DOMAIN-SUFFIX,imrworldwide.com
DOMAIN-SUFFIX,inmobi.com
DOMAIN-SUFFIX,inner-active.mobi
DOMAIN-SUFFIX,intentiq.com
DOMAIN-SUFFIX,inter1ads.com
DOMAIN-SUFFIX,ipredictive.com
DOMAIN-SUFFIX,ironsrc.com
DOMAIN-SUFFIX,iskyworker.com
DOMAIN-SUFFIX,jizzads.com
DOMAIN-SUFFIX,juicyads.com
DOMAIN-SUFFIX,kochava.com
DOMAIN-SUFFIX,leadbolt.com
DOMAIN-SUFFIX,leadbolt.net
DOMAIN-SUFFIX,leadboltads.net
DOMAIN-SUFFIX,leadboltapps.net
DOMAIN-SUFFIX,leadboltmobile.net
DOMAIN-SUFFIX,lenzmx.com
DOMAIN-SUFFIX,liveadvert.com
DOMAIN-SUFFIX,marketgid.com
DOMAIN-SUFFIX,marketo.com
DOMAIN-SUFFIX,mdotm.com
DOMAIN-SUFFIX,medialytics.com
DOMAIN-SUFFIX,medialytics.io
DOMAIN-SUFFIX,meetrics.com
DOMAIN-SUFFIX,meetrics.net
DOMAIN-SUFFIX,mgid.com
DOMAIN-SUFFIX,millennialmedia.com
DOMAIN-SUFFIX,mobadme.jp
DOMAIN-SUFFIX,mobfox.com
DOMAIN-SUFFIX,mobileadtrading.com
DOMAIN-SUFFIX,mobilityware.com
DOMAIN-SUFFIX,mojiva.com
DOMAIN-SUFFIX,mookie1.com
DOMAIN-SUFFIX,msads.net
DOMAIN-SUFFIX,mydas.mobi
DOMAIN-SUFFIX,nend.net
DOMAIN-SUFFIX,netshelter.net
DOMAIN-SUFFIX,nexage.com
DOMAIN-SUFFIX,owneriq.net
DOMAIN-SUFFIX,pixels.asia
DOMAIN-SUFFIX,plista.com
DOMAIN-SUFFIX,popads.net
DOMAIN-SUFFIX,powerlinks.com
DOMAIN-SUFFIX,propellerads.com
DOMAIN-SUFFIX,quantserve.com
DOMAIN-SUFFIX,rayjump.com
DOMAIN-SUFFIX,revdepo.com
DOMAIN-SUFFIX,rubiconproject.com
DOMAIN-SUFFIX,sape.ru
DOMAIN-SUFFIX,scorecardresearch.com
DOMAIN-SUFFIX,segment.com
DOMAIN-SUFFIX,serving-sys.com
DOMAIN-SUFFIX,sharethis.com
DOMAIN-SUFFIX,smaato.com
DOMAIN-SUFFIX,smaato.net
DOMAIN-SUFFIX,smartadserver.com
DOMAIN-SUFFIX,smartnews-ads.com
DOMAIN-SUFFIX,startapp.com
DOMAIN-SUFFIX,startappexchange.com
DOMAIN-SUFFIX,statcounter.com
DOMAIN-SUFFIX,steelhousemedia.com
DOMAIN-SUFFIX,stickyadstv.com
DOMAIN-SUFFIX,supersonic.com
DOMAIN-SUFFIX,taboola.com
DOMAIN-SUFFIX,tapjoy.com
DOMAIN-SUFFIX,tapjoyads.com
DOMAIN-SUFFIX,trafficjunky.com
DOMAIN-SUFFIX,trafficjunky.net
DOMAIN-SUFFIX,tribalfusion.com
DOMAIN-SUFFIX,turn.com
DOMAIN-SUFFIX,uberads.com
DOMAIN-SUFFIX,vidoomy.com
DOMAIN-SUFFIX,viglink.com
DOMAIN-SUFFIX,voicefive.com
DOMAIN-SUFFIX,wedolook.com
DOMAIN-SUFFIX,yadro.ru
DOMAIN-SUFFIX,yengo.com
DOMAIN-SUFFIX,zedo.com
DOMAIN-SUFFIX,zemanta.com

# baidu
DOMAIN-SUFFIX,bdstudynews.com
DOMAIN-SUFFIX,bdtdat652.shop
DOMAIN-SUFFIX,bdv5.cc
DOMAIN-SUFFIX,bdvpromociona.com
DOMAIN-SUFFIX,bdxhujrned.buzz
DOMAIN-SUFFIX,ae.bdstatic.com
DOMAIN-SUFFIX,code.bdstatic.com
DOMAIN-SUFFIX,dss2.bdstatic.com
DOMAIN-SUFFIX,fex.bdstatic.com
DOMAIN-SUFFIX,mipcache.bdstatic.com
DOMAIN-SUFFIX,sofire.bdstatic.com
DOMAIN-SUFFIX,su.bdstatic.com
DOMAIN-SUFFIX,zz.bdstatic.com
DOMAIN-SUFFIX,a.baidu.com
DOMAIN-SUFFIX,activity.baidu.com
DOMAIN-SUFFIX,ada.baidu.com
DOMAIN-SUFFIX,adavideo.baidu.com
DOMAIN-SUFFIX,adm.baidu.com
DOMAIN-SUFFIX,adscdn.baidu.com
DOMAIN-SUFFIX,afd.baidu.com
DOMAIN-SUFFIX,als.baidu.com
DOMAIN-SUFFIX,androidapp.baidu.com
DOMAIN-SUFFIX,anquan.baidu.com
DOMAIN-SUFFIX,anti-bot.baidu.com
DOMAIN-SUFFIX,antivirus.baidu.com
DOMAIN-SUFFIX,appc.baidu.com
DOMAIN-SUFFIX,as.baidu.com
DOMAIN-SUFFIX,as1.wenku.baidu.com
DOMAIN-SUFFIX,baichuan.baidu.com
DOMAIN-SUFFIX,baifen.music.baidu.com
DOMAIN-SUFFIX,bar.baidu.com
DOMAIN-SUFFIX,bdbus-turbonet.baidu.com
DOMAIN-SUFFIX,bes-mtj.baidu.com
DOMAIN-SUFFIX,bgg.baidu.com
DOMAIN-SUFFIX,br.baidu.com
DOMAIN-SUFFIX,browserkernel.baidu.com
DOMAIN-SUFFIX,bz-ipdx.baidu.com
DOMAIN-SUFFIX,bzclk.baidu.com
DOMAIN-SUFFIX,c.baidu.com
DOMAIN-SUFFIX,caclick.baidu.com
DOMAIN-SUFFIX,cb.baidu.com
DOMAIN-SUFFIX,cbjs.baidu.com
DOMAIN-SUFFIX,cdn-haokanapk.baidu.com
DOMAIN-SUFFIX,click.bes.baidu.com
DOMAIN-SUFFIX,client.baidu.com
DOMAIN-SUFFIX,cm.baidu.com
DOMAIN-SUFFIX,collector.dcdn.baidu.com
DOMAIN-SUFFIX,cpro.baidu.com
DOMAIN-SUFFIX,cpro.zhidao.baidu.com
DOMAIN-SUFFIX,cpu.baidu.com
DOMAIN-SUFFIX,cpu-openapi.baidu.com
DOMAIN-SUFFIX,cpucdn.baidu.com
DOMAIN-SUFFIX,crab.baidu.com
DOMAIN-SUFFIX,crs.baidu.com
DOMAIN-SUFFIX,cstm.baidu.com
DOMAIN-SUFFIX,daup.map.baidu.com
DOMAIN-SUFFIX,dj1.baidu.com
DOMAIN-SUFFIX,dl-vip.bav.baidu.com
DOMAIN-SUFFIX,dl.ops.baidu.com
DOMAIN-SUFFIX,dl2.bav.baidu.com
DOMAIN-SUFFIX,dlswbr.baidu.com
DOMAIN-SUFFIX,download.bav.baidu.com
DOMAIN-SUFFIX,download.sd.baidu.com
DOMAIN-SUFFIX,dss3.baidu.com
DOMAIN-SUFFIX,dxp.baidu.com
DOMAIN-SUFFIX,e.baidu.com
DOMAIN-SUFFIX,eclick.baidu.com
DOMAIN-SUFFIX,eduad.baidu.com
DOMAIN-SUFFIX,eiv.baidu.com
DOMAIN-SUFFIX,em.baidu.com
DOMAIN-SUFFIX,entry.baidu.com
DOMAIN-SUFFIX,ers.baidu.com
DOMAIN-SUFFIX,ext.baidu.com
DOMAIN-SUFFIX,f10.baidu.com
DOMAIN-SUFFIX,f11.baidu.com
DOMAIN-SUFFIX,fc1tn.baidu.com
DOMAIN-SUFFIX,fc2tn.baidu.com
DOMAIN-SUFFIX,fc3tn.baidu.com
DOMAIN-SUFFIX,fc4tn.baidu.com
DOMAIN-SUFFIX,fc5tn.baidu.com
DOMAIN-SUFFIX,fclick.baidu.com
DOMAIN-SUFFIX,fclog.baidu.com
DOMAIN-SUFFIX,feed.baidu.com
DOMAIN-SUFFIX,feed-image.baidu.com
DOMAIN-SUFFIX,fexclick.baidu.com
DOMAIN-SUFFIX,fxgate.baidu.com
DOMAIN-SUFFIX,g.baidu.com
DOMAIN-SUFFIX,gdown.baidu.com
DOMAIN-SUFFIX,gimg.baidu.com
DOMAIN-SUFFIX,gips1.baidu.com
DOMAIN-SUFFIX,gips2.baidu.com
DOMAIN-SUFFIX,goutong.baidu.com
DOMAIN-SUFFIX,gsp0.baidu.com
DOMAIN-SUFFIX,gsp1.baidu.com
DOMAIN-SUFFIX,haoma.baidu.com
DOMAIN-SUFFIX,hcl.baidu.com
DOMAIN-SUFFIX,hdj.baidu.com
DOMAIN-SUFFIX,hector.baidu.com
DOMAIN-SUFFIX,hectorstatic.baidu.com
DOMAIN-SUFFIX,hijack.baidu.com
DOMAIN-SUFFIX,hm.baidu.com
DOMAIN-SUFFIX,hmma.baidu.com
DOMAIN-SUFFIX,hpd.baidu.com
DOMAIN-SUFFIX,httpdns.baidu.com
DOMAIN-SUFFIX,httpsdns.baidu.com
DOMAIN-SUFFIX,idm-su.baidu.com
DOMAIN-SUFFIX,idm.bce.baidu.com
DOMAIN-SUFFIX,im.tieba.baidu.com
DOMAIN-SUFFIX,imgstat.baidu.com
DOMAIN-SUFFIX,inside.baidu.com
DOMAIN-SUFFIX,isite.baidu.com
DOMAIN-SUFFIX,itsdata.map.baidu.com
DOMAIN-SUFFIX,jmy-pic.baidu.com
DOMAIN-SUFFIX,jzapi.baidu.com
DOMAIN-SUFFIX,kstj.baidu.com
DOMAIN-SUFFIX,lbsonline.pushct.baidu.com
DOMAIN-SUFFIX,leads.baidu.com
DOMAIN-SUFFIX,log.music.baidu.com
DOMAIN-SUFFIX,lookup.api.bsb.baidu.com
DOMAIN-SUFFIX,luimg.baidu.com
DOMAIN-SUFFIX,m1.baidu.com
DOMAIN-SUFFIX,miao.baidu.com
DOMAIN-SUFFIX,mime.baidu.com
DOMAIN-SUFFIX,mipengine.baidu.com
DOMAIN-SUFFIX,mo.baidu.com
DOMAIN-SUFFIX,mobads.baidu.com
DOMAIN-SUFFIX,mobads-logs.baidu.com
DOMAIN-SUFFIX,mobile-global.baidu.com
DOMAIN-SUFFIX,mobopay.baidu.com
DOMAIN-SUFFIX,mountain.zhidao.baidu.com
DOMAIN-SUFFIX,msc.baidu.com
DOMAIN-SUFFIX,mscbos.baidu.com
DOMAIN-SUFFIX,msite.baidu.com
DOMAIN-SUFFIX,mssp.baidu.com
DOMAIN-SUFFIX,mtj.baidu.com
DOMAIN-SUFFIX,nadvideo.baidu.com
DOMAIN-SUFFIX,nadvideo2.baidu.com
DOMAIN-SUFFIX,newclient.map.baidu.com
DOMAIN-SUFFIX,newvector.map.baidu.com
DOMAIN-SUFFIX,nlog.baidu.com
DOMAIN-SUFFIX,nsclickvideo.baidu.com
DOMAIN-SUFFIX,offnavi.map.baidu.com
DOMAIN-SUFFIX,ofloc.map.baidu.com
DOMAIN-SUFFIX,olimenew.baidu.com
DOMAIN-SUFFIX,openrcv.baidu.com
DOMAIN-SUFFIX,paimgcdn-feed.baidu.com
DOMAIN-SUFFIX,pcappstore.baidu.com
DOMAIN-SUFFIX,pcrec.baidu.com
DOMAIN-SUFFIX,pimlog.baidu.com
DOMAIN-SUFFIX,pos.baidu.com
DOMAIN-SUFFIX,ps.map.baidu.com
DOMAIN-SUFFIX,publish-pic-cpu.baidu.com
DOMAIN-SUFFIX,pups.baidu.com
DOMAIN-SUFFIX,qapm.baidu.com
DOMAIN-SUFFIX,qianclick.baidu.com
DOMAIN-SUFFIX,qiao.baidu.com
DOMAIN-SUFFIX,release.baidu.com
DOMAIN-SUFFIX,report-uri.baidu.com
DOMAIN-SUFFIX,res.mi.baidu.com
DOMAIN-SUFFIX,river.zhidao.baidu.com
DOMAIN-SUFFIX,sclick.baidu.com
DOMAIN-SUFFIX,sepro.baidu.com
DOMAIN-SUFFIX,sestat.baidu.com
DOMAIN-SUFFIX,sfp.safe.baidu.com
DOMAIN-SUFFIX,shadu.baidu.com
DOMAIN-SUFFIX,share.baidu.com
DOMAIN-SUFFIX,sjh.baidu.com
DOMAIN-SUFFIX,sobar.baidu.com
DOMAIN-SUFFIX,sofire.baidu.com
DOMAIN-SUFFIX,sp0.baidu.com
DOMAIN-SUFFIX,sp1.baidu.com
DOMAIN-SUFFIX,sp2.baidu.com
DOMAIN-SUFFIX,sp3.baidu.com
DOMAIN-SUFFIX,stat.v.baidu.com
DOMAIN-SUFFIX,static.tieba.baidu.com
DOMAIN-SUFFIX,statsonline.pushct.baidu.com
DOMAIN-SUFFIX,sv.map.baidu.com
DOMAIN-SUFFIX,tcbox.baidu.com
DOMAIN-SUFFIX,techain.baidu.com
DOMAIN-SUFFIX,tongji.baidu.com
DOMAIN-SUFFIX,toolbar.baidu.com
DOMAIN-SUFFIX,tracker.dcdn.baidu.com
DOMAIN-SUFFIX,tuijian.baidu.com
DOMAIN-SUFFIX,tuisong.baidu.com
DOMAIN-SUFFIX,udc.safe.baidu.com
DOMAIN-SUFFIX,udpolimenew.baidu.com
DOMAIN-SUFFIX,udpolimeok.baidu.com
DOMAIN-SUFFIX,ufosdk.baidu.com
DOMAIN-SUFFIX,ug.baidu.com
DOMAIN-SUFFIX,ulog.imap.baidu.com
DOMAIN-SUFFIX,union.baidu.com
DOMAIN-SUFFIX,unionimage.baidu.com
DOMAIN-SUFFIX,unionsug.baidu.com
DOMAIN-SUFFIX,update.pan.baidu.com
DOMAIN-SUFFIX,usp1.baidu.com
DOMAIN-SUFFIX,usug.baidu.com
DOMAIN-SUFFIX,utility.baidu.com
DOMAIN-SUFFIX,wanba.baidu.com
DOMAIN-SUFFIX,wangmeng.baidu.com
DOMAIN-SUFFIX,weishi.baidu.com
DOMAIN-SUFFIX,wjz-cdn.baidu.com
DOMAIN-SUFFIX,wkclick.baidu.com
DOMAIN-SUFFIX,wkctj.baidu.com
DOMAIN-SUFFIX,wm.baidu.com
DOMAIN-SUFFIX,yingxiao.baidu.com
DOMAIN-SUFFIX,youxi.baidu.com
DOMAIN-SUFFIX,zhanzhang.baidu.com
DOMAIN-SUFFIX,znsv.baidu.com

# taobao
DOMAIN-SUFFIX,wcp.taobao.com
DOMAIN-SUFFIX,accscdn.m.taobao.com
DOMAIN-SUFFIX,acookie.taobao.com
DOMAIN-SUFFIX,acs.m.taobao.com
DOMAIN-SUFFIX,acs4baichuan.m.taobao.com
DOMAIN-SUFFIX,adash-c.m.taobao.com
DOMAIN-SUFFIX,adash-c.ut.taobao.com
DOMAIN-SUFFIX,adash.m.taobao.com
DOMAIN-SUFFIX,adashbc.m.taobao.com
DOMAIN-SUFFIX,adashbc.ut.taobao.com
DOMAIN-SUFFIX,adashx.m.taobao.com
DOMAIN-SUFFIX,adashx.ut.taobao.com
DOMAIN-SUFFIX,adashx4ae.ut.taobao.com
DOMAIN-SUFFIX,adashx4sg.ut.taobao.com
DOMAIN-SUFFIX,adashx4yt.m.taobao.com
DOMAIN-SUFFIX,adashxgc.ut.taobao.com
DOMAIN-SUFFIX,agoo-report.m.taobao.com
DOMAIN-SUFFIX,agoodm.m.taobao.com
DOMAIN-SUFFIX,ai.taobao.com
DOMAIN-SUFFIX,ai.m.taobao.com
DOMAIN-SUFFIX,ald.taobao.com
DOMAIN-SUFFIX,amdc.m.taobao.com
DOMAIN-SUFFIX,amdcopen.m.taobao.com
DOMAIN-SUFFIX,audid-api.taobao.com
DOMAIN-SUFFIX,audid-api-sg.taobao.com
DOMAIN-SUFFIX,baichuan-sdk.taobao.com
DOMAIN-SUFFIX,bcfeedback.taobao.com
DOMAIN-SUFFIX,c-adash.m.taobao.com
DOMAIN-SUFFIX,click.tz.simba.taobao.com
DOMAIN-SUFFIX,detail.taobao.com
DOMAIN-SUFFIX,dsp.simba.taobao.com
DOMAIN-SUFFIX,eco.taobao.com
DOMAIN-SUFFIX,err.taobao.com
DOMAIN-SUFFIX,fav.simba.taobao.com
DOMAIN-SUFFIX,fourier.taobao.com
DOMAIN-SUFFIX,g.click.taobao.com
DOMAIN-SUFFIX,gaode-acs.m.taobao.com
DOMAIN-SUFFIX,gaode-jmacs.m.taobao.com
DOMAIN-SUFFIX,global.click.taobao.com
DOMAIN-SUFFIX,h-adashx.ut.taobao.com
DOMAIN-SUFFIX,h-adashx4ae.ut.taobao.com
DOMAIN-SUFFIX,h-adashx4bc.ut.taobao.com
DOMAIN-SUFFIX,h-adashx4sg.ut.taobao.com
DOMAIN-SUFFIX,h-adashx4yt.ut.taobao.com
DOMAIN-SUFFIX,huodong.m.taobao.com
DOMAIN-SUFFIX,hybrid.miniapp.taobao.com
DOMAIN-SUFFIX,ip.taobao.com
DOMAIN-SUFFIX,ju.taobao.com
DOMAIN-SUFFIX,m-adash.m.taobao.com
DOMAIN-SUFFIX,m.simba.taobao.com
DOMAIN-SUFFIX,mamasearchad.cloudvideocdn.taobao.com
DOMAIN-SUFFIX,mclick.simba.taobao.com
DOMAIN-SUFFIX,metric.webv.taobao.com
DOMAIN-SUFFIX,mpp.taobao.com
DOMAIN-SUFFIX,nbsdk-baichuan.taobao.com
DOMAIN-SUFFIX,openjmacs.m.taobao.com
DOMAIN-SUFFIX,pcookie.taobao.com
DOMAIN-SUFFIX,re.taobao.com
DOMAIN-SUFFIX,re.m.taobao.com
DOMAIN-SUFFIX,redirect.simba.taobao.com
DOMAIN-SUFFIX,retcode.taobao.com
DOMAIN-SUFFIX,rj.m.taobao.com
DOMAIN-SUFFIX,s8.taobao.com
DOMAIN-SUFFIX,sdkinit.taobao.com
DOMAIN-SUFFIX,shop115048570.taobao.com
DOMAIN-SUFFIX,simaba.taobao.com
DOMAIN-SUFFIX,simaba.m.taobao.com
DOMAIN-SUFFIX,simba.m.taobao.com
DOMAIN-SUFFIX,sjarvis.taobao.com
DOMAIN-SUFFIX,srd.simba.taobao.com
DOMAIN-SUFFIX,stat.simba.taobao.com
DOMAIN-SUFFIX,tejia.taobao.com
DOMAIN-SUFFIX,temai.taobao.com
DOMAIN-SUFFIX,textlink.simba.taobao.com
DOMAIN-SUFFIX,tns.simba.taobao.com
DOMAIN-SUFFIX,trade-acs.m.taobao.com
DOMAIN-SUFFIX,tui.taobao.com
DOMAIN-SUFFIX,tunion-api.m.taobao.com
DOMAIN-SUFFIX,tyh.taobao.com
DOMAIN-SUFFIX,umengacs.m.taobao.com
DOMAIN-SUFFIX,umengjmacs.m.taobao.com
DOMAIN-SUFFIX,w.m.taobao.com
DOMAIN-SUFFIX,wb.110.taobao.com
DOMAIN-SUFFIX,wcp.taobao.com
DOMAIN-SUFFIX,xjp-jmacs.m.taobao.com
DOMAIN-SUFFIX,xjp-msgacs.m.taobao.com
DOMAIN-SUFFIX,youku-acs.m.taobao.com
DOMAIN-SUFFIX,strip.taobaocdn.com

# tencent
DOMAIN-SUFFIX,report.meeting.tencent.com
DOMAIN-SUFFIX,report.trade.weixin.qq.com
DOMAIN-SUFFIX,ad.weixin.qq.com
DOMAIN-SUFFIX,as.weixin.qq.com
DOMAIN-SUFFIX,dns.weixin.qq.com
DOMAIN-SUFFIX,ad.qq.com
DOMAIN-SUFFIX,adfilter.imtt.qq.com
DOMAIN-SUFFIX,adsfile.qq.com
DOMAIN-SUFFIX,adslvfile.qq.com
DOMAIN-SUFFIX,aegis.qq.com
DOMAIN-SUFFIX,appcfg.v.qq.com
DOMAIN-SUFFIX,beacon.qq.com
DOMAIN-SUFFIX,beaconcdn.qq.com
DOMAIN-SUFFIX,bsrv.qq.com
DOMAIN-SUFFIX,bugly.qq.com
DOMAIN-SUFFIX,c.gj.qq.com
DOMAIN-SUFFIX,c2.gdt.qq.com
DOMAIN-SUFFIX,canvas-cdn.gdt.qq.com
DOMAIN-SUFFIX,cfg.imtt.qq.com
DOMAIN-SUFFIX,commdata.v.qq.com
DOMAIN-SUFFIX,file.daihuo.qq.com
DOMAIN-SUFFIX,h.trace.qq.com
DOMAIN-SUFFIX,ii.gdt.qq.com
DOMAIN-SUFFIX,jpush.html5.qq.com
DOMAIN-SUFFIX,kde.qq.com
DOMAIN-SUFFIX,lives.l.ott.video.qq.com
DOMAIN-SUFFIX,log.tbs.qq.com
DOMAIN-SUFFIX,m.kubiqq.com
DOMAIN-SUFFIX,masdkv6.3g.qq.com
DOMAIN-SUFFIX,mazu.m.qq.com
DOMAIN-SUFFIX,mi.gdt.qq.com
DOMAIN-SUFFIX,monitor.music.qq.com
DOMAIN-SUFFIX,monitor.uu.qq.com
DOMAIN-SUFFIX,oth.eve.mdt.qq.com
DOMAIN-SUFFIX,oth.str.mdt.qq.com
DOMAIN-SUFFIX,p.l.qq.com
DOMAIN-SUFFIX,pcm-img.zhls.qq.com
DOMAIN-SUFFIX,pms.mb.qq.com
DOMAIN-SUFFIX,q.i.gdt.qq.com
DOMAIN-SUFFIX,qqdata.ab.qq.com
DOMAIN-SUFFIX,report.tv.kohesport.qq.com
DOMAIN-SUFFIX,rpt.gdt.qq.com
DOMAIN-SUFFIX,s1.qq.com
DOMAIN-SUFFIX,s2.qq.com
DOMAIN-SUFFIX,s3.qq.com
DOMAIN-SUFFIX,scdown.qq.com
DOMAIN-SUFFIX,sdk.e.qq.com
DOMAIN-SUFFIX,sdkconfig.video.qq.com
DOMAIN-SUFFIX,sngmta.qq.com
DOMAIN-SUFFIX,snowflake.qq.com
DOMAIN-SUFFIX,stat.y.qq.com
DOMAIN-SUFFIX,static.wxqcloud.qq.com.cn
DOMAIN-SUFFIX,t.l.qq.com
DOMAIN-SUFFIX,tangram.e.qq.com
DOMAIN-SUFFIX,tdc.qq.com
DOMAIN-SUFFIX,tj.b.qq.com
DOMAIN-SUFFIX,tj.video.qq.com
DOMAIN-SUFFIX,tmead.y.qq.com
DOMAIN-SUFFIX,tmeadcomm.y.qq.com
DOMAIN-SUFFIX,tmfmazu-wangka.m.qq.com
DOMAIN-SUFFIX,tmfmazu.m.qq.com
DOMAIN-SUFFIX,tmfsdk.m.qq.com
DOMAIN-SUFFIX,tmfsdktcpv4.m.qq.com
DOMAIN-SUFFIX,trace.qq.com
DOMAIN-SUFFIX,us.l.qq.com
DOMAIN-SUFFIX,v2.gdt.qq.com
DOMAIN-SUFFIX,v2mi.gdt.qq.com
DOMAIN-SUFFIX,v3.gdt.qq.com
DOMAIN-SUFFIX,video.dispatch.tc.qq.com
DOMAIN-SUFFIX,vlive.qqvideo.tc.qq.com
DOMAIN-SUFFIX,w.l.qq.com
DOMAIN-SUFFIX,win.gdt.qq.com
DOMAIN-SUFFIX,ws.sj.qq.com
DOMAIN-SUFFIX,wxa.wxs.qq.com
DOMAIN-SUFFIX,wxaintpcos.wxqcloud.qq.com.cn
DOMAIN-SUFFIX,wximg.wxs.qq.com
DOMAIN-SUFFIX,wxsmw.wxs.qq.com
DOMAIN-SUFFIX,wxsnsad.tc.qq.com
DOMAIN-SUFFIX,wxsnsdy.tc.qq.com
DOMAIN-SUFFIX,wxsnsdy.wxs.qq.com
DOMAIN-SUFFIX,wxsnsdythumb.wxs.qq.com
DOMAIN-SUFFIX,xc.gdt.qq.com

# miui
DOMAIN-SUFFIX,tracking.miui.com
DOMAIN-SUFFIX,data.mistat.xiaomi.com
DOMAIN-SUFFIX,diagnosis.ad.xiaomi.com
DOMAIN-SUFFIX,log.ad.xiaomi.com
DOMAIN-SUFFIX,m.track.ad.xiaomi.com
DOMAIN-SUFFIX,sdkconfig.ad.xiaomi.com
DOMAIN-SUFFIX,api.ad.xiaomi.com
DOMAIN-SUFFIX,tracker.ai.xiaomi.com
grayconfig.ai.xiaomi.com
