# P2P
PROCESS-NAME,*Folx*
PROCESS-NAME,*Thunder*
PROCESS-NAME,*DownloadService*
PROCESS-NAME,*Soda*
PROCESS-NAME,*p4pclient*
PROCESS-NAME,aria2c
PROCESS-NAME,fdm
PROCESS-NAME,Folx
PROCESS-NAME,NetTransport
PROCESS-NAME,Transmission
PROCESS-NAME,uTorrent
PROCESS-NAME,WebTorrent
PROCESS-NAME,WebTorrent Helper
DOMAIN-KEYWORD,tracker

# dns
IP-CIDR,1.1.1.1/32
IP-CIDR,1.0.0.1/32
IP-CIDR,205.198.85.43/32

# Misc
DOMAIN-SUFFIX,qq.com
DOMAIN-KEYWORD,syncthing
DOMAIN-KEYWORD,alibaba-inc
DOMAIN-KEYWORD,alibaba
DOMAIN-KEYWORD,alipay-inc
DOMAIN-KEYWORD,aliyuncs
DOMAIN-KEYWORD,alipay
DOMAIN-KEYWORD,taobao
DOMAIN-KEYWORD,alicdn
DOMAIN-KEYWORD,aliyun
DOMAIN-KEYWORD,9game
DOMAIN-KEYWORD,ucweb
DOMAIN-SUFFIX,digicert.com
DOMAIN-SUFFIX,ipify.org
DOMAIN-SUFFIX,hifini.com

# Synology
DOMAIN-KEYWORD,quickconnect
DOMAIN-KEYWORD,synology
DOMAIN-SUFFIX,dyndns.org
DOMAIN-SUFFIX,dyndns.com
DOMAIN-SUFFIX,akamai.com

# Apple
DOMAIN-SUFFIX,apple.com.cn
DOMAIN-SUFFIX,apple.com
DOMAIN-SUFFIX,icloud.com.cn
DOMAIN-SUFFIX,icloud.com
